# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar_day',
            field=models.DateField(db_index=True),
        ),
    ]
