# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Gewünschter Eintrittstermin')),
                ('time_from', models.TimeField(default=datetime.time(9, 0), verbose_name='Betreuungszeit von:')),
                ('time_to', models.TimeField(default=datetime.time(17, 0), verbose_name='Betreuungszeit bis:')),
                ('child_pre_name', models.CharField(max_length=255, verbose_name='Vorname des Kindes')),
                ('child_name', models.CharField(max_length=255, verbose_name='Nachname des Kindes')),
                ('birth_date', models.DateField(verbose_name='Geburtstag bzw Termin')),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='Geschlecht')),
                ('nationality', models.CharField(default='DE', max_length=2, verbose_name='Staatsangeörigkeit')),
                ('father_name', models.CharField(max_length=255, verbose_name='Vor- und Nachname des Vater')),
                ('father_profession', models.CharField(max_length=255, verbose_name='Beruf des Vaters')),
                ('father_nationality', models.CharField(default='DE', max_length=2, verbose_name='Staatsangeörigkeit des Vaters')),
                ('father_legal', models.CharField(default='verheiratet', max_length=64, verbose_name='Familienstand des Vaters')),
                ('father_mobile', models.CharField(max_length=255, verbose_name='Handynummer des Vaters')),
                ('father_email', models.EmailField(max_length=254, verbose_name='Email des Vaters')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Vor- und Nachname der Mutter')),
                ('mother_profession', models.CharField(max_length=255, verbose_name='Beruf der Mutter')),
                ('mother_nationality', models.CharField(default='DE', max_length=2, verbose_name='Staatsangeörigkeit der Mutter')),
                ('mother_legal', models.CharField(default='verheiratet', max_length=64, verbose_name='Familienstand der Mutter')),
                ('mother_mobile', models.CharField(max_length=255, verbose_name='Handynummer der Mutter')),
                ('mother_email', models.EmailField(max_length=254, verbose_name='Email der Mutter')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('number', models.CharField(max_length=64, verbose_name='Hausnummer')),
                ('zip', models.CharField(max_length=64, verbose_name='Postleitzahl')),
                ('city', models.CharField(max_length=64, verbose_name='Stadt')),
                ('fon', models.CharField(max_length=64, verbose_name='Telefonnummer')),
                ('email', models.EmailField(max_length=254, verbose_name='Email für die Korrespondenz')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Anmerkungen')),
                ('urgency', models.CharField(choices=[('A', 'Familien, die gemäß §27 i.V.m.§36 SGB VIII der „Hilfe zur Erziehung“ bedürfen'), ('B', 'Kinder, deren Mutter oder Vater alleinerziehend und berufstätig oder \nin Ausbildung ist, sowie Kinder deren beide Elternteile berufstätig oder in Ausbildung sind, soweit Umfang und\nLage der Arbeitszeit bzw. Unterrichtszeit die Betreuung erforderlich machen'), ('S', 'Soziale Härtefälle')], max_length=1, verbose_name='Dringlichkeit')),
                ('privacy', models.BooleanField()),
                ('data_protection', models.BooleanField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(editable=False, max_length=64)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('original_time', models.CharField(default='', editable=False, max_length=64)),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
