# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='urgency',
            field=models.CharField(choices=[('A', '§27 i.V.m. §36'), ('B', 'Alleinerziehend'), ('S', 'Soziale Härtefälle')], max_length=1, verbose_name='Dringlichkeit'),
        ),
    ]
